# Generated by Django 6.1 on 2026-09-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosalert',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='sosalert',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical Emergency'), ('fall', 'Fall/Accident'), ('security', 'Security Concern'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('active_response', 'Active Response'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
