# Generated by Django 6.1 on 2026-09-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
