# Generated by Django 6.1 on 2026-09-22 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_incidenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='secondary_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_guardian_of_flat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EscalationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_timeout_seconds', models.IntegerField(default=60)),
                ('primary_guardian_enabled', models.BooleanField(default=True)),
                ('secondary_guardian_enabled', models.BooleanField(default=True)),
                ('emergency_contact_enabled', models.BooleanField(default=True)),
                ('gated_society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_config', to='accounts.gatedsociety')),
            ],
        ),
    ]
