# Generated by Django 6.1 on 2026-09-22 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_is_available_customuser_last_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.sosalert')),
            ],
        ),
    ]
