# Generated by Django 6.1 on 2026-09-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_incidentmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_available',
            new_name='available',
        ),
    ]
