# Generated by Django 6.0.8 on 2026-09-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_is_available_customuser_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='escalation_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='last_stage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
